# Generated by Django 2.1 on 2018-08-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name',
            name='buyer',
            field=models.BooleanField(),
        ),
    ]
