# Generated by Django 2.1 on 2018-08-13 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0002_auto_20180808_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTelegramBot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('buyer', models.BooleanField(default=False)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=100)),
                ('counter', models.IntegerField()),
                ('user_telegram_bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='green_bot_app.Organisation')),
            ],
        ),
        migrations.DeleteModel(
            name='Name',
        ),
    ]
