# Generated by Django 2.1 on 2018-09-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0002_auto_20180830_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doorusage',
            name='opened_door_time',
            field=models.DateTimeField(blank=True, verbose_name='success_request'),
        ),
    ]
