# Generated by Django 2.1 on 2018-08-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0003_auto_20180813_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
