# Generated by Django 2.1 on 2018-08-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0004_auto_20180813_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user_telegram_bot',
        ),
    ]
