# Generated by Django 2.1 on 2018-08-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0005_auto_20180813_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='message_id',
            field=models.IntegerField(null=True),
        ),
    ]
