# Generated by Django 2.1 on 2018-08-20 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('green_bot_app', '0007_telegramuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
